# Generated by Django 5.2.8 on 2026-01-29 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='override_frais_inscription_du',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='inscription',
            name='override_frais_scolarite_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='inscription',
            name='tarif_override',
            field=models.BooleanField(default=False),
        ),
    ]
