# Generated by Django 5.2.8 on 2026-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inscription_override_frais_inscription_du_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='batch_token',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
