# Generated by Django 5.2.8 on 2026-02-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_absence_archived_at_absenceprof_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfinance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.parent'),
        ),
    ]
