# Generated by Django 5.2.8 on 2026-01-29 19:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paiement_batch_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_paiement', to='core.echeancemensuelle')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.paiement')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('paiement', 'echeance'), name='unique_ligne_paiement_echeance')],
            },
        ),
    ]
