# Generated by Django 5.2.8 on 2026-01-31 01:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paiementligne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echeancemensuelle',
            options={'ordering': ['mois_index', 'id']},
        ),
        migrations.CreateModel(
            name='TransactionFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('SCOLARITE', 'Scolarité')], default='SCOLARITE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('batch_token', models.CharField(blank=True, db_index=True, max_length=36)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.inscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_transaction', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=120)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_lignes', to='core.echeancemensuelle')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.transactionfinance')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'echeance'), name='unique_tx_echeance_par_transaction')],
            },
        ),
    ]
