# Generated by Django 5.2.8 on 2026-02-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_tx_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire', unique=True)),
            ],
        ),
    ]
