# Generated by Django 5.2.8 on 2026-01-31 17:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_echeancemensuelle_options_transactionfinance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceTransportMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_index', models.PositiveSmallIntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='A_PAYER', max_length=10)),
            ],
            options={
                'ordering': ['mois_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EleveTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('tarif_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='transactionligne',
            name='unique_tx_echeance_par_transaction',
        ),
        migrations.AlterField(
            model_name='transactionfinance',
            name='type_transaction',
            field=models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('SCOLARITE', 'Scolarité'), ('TRANSPORT', 'Transport'), ('PACK', 'Pack')], default='SCOLARITE', max_length=20),
        ),
        migrations.AddField(
            model_name='echeancetransportmensuelle',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances_transport', to='core.anneescolaire'),
        ),
        migrations.AddField(
            model_name='echeancetransportmensuelle',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_transport', to='core.eleve'),
        ),
        migrations.AddField(
            model_name='echeancetransportmensuelle',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='echeances_transport', to='core.groupe'),
        ),
        migrations.AddField(
            model_name='transactionligne',
            name='echeance_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_lignes_transport', to='core.echeancetransportmensuelle'),
        ),
        migrations.AddConstraint(
            model_name='transactionligne',
            constraint=models.UniqueConstraint(condition=models.Q(('echeance__isnull', False)), fields=('transaction', 'echeance'), name='unique_tx_sco_echeance'),
        ),
        migrations.AddConstraint(
            model_name='transactionligne',
            constraint=models.UniqueConstraint(condition=models.Q(('echeance_transport__isnull', False)), fields=('transaction', 'echeance_transport'), name='unique_tx_tr_echeance'),
        ),
        migrations.AddConstraint(
            model_name='transactionligne',
            constraint=models.CheckConstraint(condition=models.Q(('echeance__isnull', False), ('echeance_transport__isnull', False), _negated=True), name='ck_txligne_not_both_echeances'),
        ),
        migrations.AddField(
            model_name='elevetransport',
            name='eleve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='core.eleve'),
        ),
        migrations.AddConstraint(
            model_name='echeancetransportmensuelle',
            constraint=models.UniqueConstraint(fields=('eleve', 'annee', 'mois_index'), name='unique_transport_eleve_annee_mois'),
        ),
    ]
