# Generated by Django 5.2.8 on 2026-02-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recucounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recucounter',
            name='annee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu_counter', to='core.anneescolaire'),
        ),
    ]
