# Generated by Django 5.2.8 on 2026-01-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remboursement_remboursementligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfinance',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_finance', to='core.paiement'),
        ),
    ]
