# Generated by Django 5.2.8 on 2026-02-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_recucounter_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='telephone_norm',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
