# Generated by Django 5.2.8 on 2026-02-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parent_telephone_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='dernier_etablissement',
            field=models.CharField(blank=True, default='', help_text='Dernier établissement fréquenté', max_length=160),
        ),
    ]
