# Generated by Django 5.2.8 on 2026-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inscription_dernier_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfinance',
            name='receipt_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
