# Generated by Django 5.2.8 on 2026-02-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_remboursementligne_remboursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursementfinance',
            name='is_annulation',
            field=models.BooleanField(default=False),
        ),
    ]
