# Generated by Django 5.2.8 on 2026-02-16 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transactionfinance_receipt_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20),
        ),
        migrations.AlterField(
            model_name='remboursementfinance',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionfinance',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20),
        ),
        migrations.CreateModel(
            name='TransactionJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('RECU', 'Reçu / Bordereau'), ('CHEQUE', 'Chèque (scan)'), ('VIREMENT', 'Virement (preuve)'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to='finance/transactions/justificatifs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='core.transactionfinance')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
