# Generated by Django 5.2.8 on 2026-02-01 03:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remboursementfinance_is_annulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfinance',
            name='paiement',
        ),
        migrations.AlterField(
            model_name='remboursementfinance',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
