# Generated by Django 5.2.8 on 2026-02-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transactionfinance_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantgroupe',
            name='matiere_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_temp', to='core.matiere'),
        ),
    ]
