# Generated by Django 5.2.8 on 2026-02-17 02:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paiement_mode_alter_remboursementfinance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('sco_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tr_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('inscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='tarification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='core.tarification'),
        ),
    ]
