# Generated by Django 5.2.8 on 2026-02-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tarification_inscription_tarification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='tarification',
        ),
        migrations.AddField(
            model_name='inscription',
            name='sco_default_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override montant mensuel scolarité pour cette inscription', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='tr_default_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override montant mensuel transport pour cette inscription', max_digits=10, null=True),
        ),
    ]
