# Generated by Django 5.2.8 on 2026-02-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_convert_enseignantgroupe_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignantgroupe',
            name='matiere_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignants_groupes', to='core.matiere'),
        ),
    ]
