# Generated by Django 5.2.8 on 2026-02-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_enseignantgroupe_matiere_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignantgroupe',
            name='matiere',
        ),
    ]
