# Generated by Django 5.2.8 on 2026-02-02 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_enseignantgroupe_matiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enseignantgroupe',
            name='unique_enseignant_groupe_annee',
        ),
        migrations.AddConstraint(
            model_name='enseignantgroupe',
            constraint=models.UniqueConstraint(fields=('annee', 'enseignant', 'groupe', 'matiere_fk'), name='unique_enseignant_groupe_annee_matiere'),
        ),
    ]
