# Generated by Django 5.2.8 on 2026-02-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_enseignantgroupe_unique_enseignant_groupe_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignantgroupe',
            name='matiere_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignants_groupes', to='core.matiere'),
            preserve_default=False,
        ),
    ]
