# Generated by Django 5.2.8 on 2026-02-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_enseignantgroupe_matiere_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profgroupe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profgroupe',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prof_groupes', to='core.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profgroupe',
            name='enseignant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prof_groupes', to='core.enseignant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_groupes', to='core.groupe'),
        ),
        migrations.AddConstraint(
            model_name='profgroupe',
            constraint=models.UniqueConstraint(fields=('annee', 'enseignant', 'groupe'), name='unique_prof_groupe_annee'),
        ),
        migrations.RemoveField(
            model_name='profgroupe',
            name='user',
        ),
    ]
