# Generated by Django 5.2.8 on 2026-02-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profgroupe_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enseignantgroupe',
            name='unique_enseignant_groupe_annee_matiere',
        ),
        migrations.RemoveConstraint(
            model_name='profgroupe',
            name='unique_prof_groupe_annee',
        ),
        migrations.RemoveField(
            model_name='profgroupe',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='profgroupe',
            name='enseignant',
        ),
        migrations.AlterField(
            model_name='enseignantgroupe',
            name='matiere_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignants_groupes', to='core.matiere'),
        ),
        migrations.AlterField(
            model_name='profgroupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe'),
        ),
        migrations.AlterField(
            model_name='profgroupe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='enseignantgroupe',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere_fk__isnull', True)), fields=('annee', 'enseignant', 'groupe'), name='unique_enseignant_groupe_annee_sans_matiere'),
        ),
        migrations.AddConstraint(
            model_name='enseignantgroupe',
            constraint=models.UniqueConstraint(condition=models.Q(('matiere_fk__isnull', False)), fields=('annee', 'enseignant', 'groupe', 'matiere_fk'), name='unique_enseignant_groupe_annee_matiere'),
        ),
        migrations.AddConstraint(
            model_name='profgroupe',
            constraint=models.UniqueConstraint(fields=('user', 'groupe'), name='unique_user_groupe'),
        ),
    ]
